### ISSUE TITLE
Remote App server calls

### ISSUE THREAD

**Issue by gerhardcit** [gioboa/sveltekit-microfrontend-demo#1]
@gioboa , this is a great example thx.
I was eagerly awaiting this sveltekit integration, but then ran into a conceptual issue which I'm wondering how it should be addressed.

Would you consider adding a +page.server.ts to the remote app.? 
How would that be loaded, since the +page.svelte is exposed in the remote app's vite.config.ts
```js
exposes: {
	'./remote-app': './src/routes/+page.svelte',
},
```

Which makes me wonder about the difference between a remote front-end and a remote-app ? Is that a thing?

My use case is a remote app that get's included (on demand) in the host app, but I want to remote app's api to still function as per normal.

What I had to do is to create a /api/remote/+server.ts in the remote app,
and then in the host app proxy api/remote to the remote app's port again. (which mean when you deploy your application router (nginx) should be handling that.

Any ideas on how the design would be for a remote app that also do it's own api or server interactions?

**Comment by gioboa** [comment]
Hi, this is an interesting use case. Can you use [excalidraw](https://excalidraw.com/) to design briefly the architecture you would like?
I'm more than happy to look at that

**Comment by gerhardcit** [comment]
This is my first idea.
https://excalidraw.com/#json=JawM3ekRFP-vR5ORmeV9k,Yz7i0lK6pMMRbEy6bc4uxQ

But now I'm also experimenting with rather doing SSR rendering on the remote app and inject that into the host.
The remote app will have some navigation and multiple pages, so I would need to be smart with that somehow.

The use case is a white labeled app, but on demand, for specific tenant, I need to include a module that is not available to other tenants. But I want to keep the "other app" logic out of the standard product.

**Comment by gioboa** [comment]
Have you tried loading the remote inside the host app and then configuring it to call the api?
eg. http://remote-url/api/list or something similar
By doing this, each loaded remote will have its own URL to call, customerA, customerB, customerC

**Comment by gerhardcit** [comment]
Yes, that's what you have to do. Catch the remote api calls locally as well.
So in my mind module federation brings in ui code and logic, but you still need to handle the remote api proxy calls.
Just wondering how far that can go?

![image](https://github.com/user-attachments/assets/233cf87f-7df6-4bc6-b90a-e728ec57f00a)

**Comment by gerhardcit** [comment]
as a fyi @gioboa , we've decided to build the remote app with Vite / svelte only (no routing). It requires a nestjs api anyway, and then build our own internal memory router to handle navigation.
One can catch the routes in the host app, but then you have to ignore/revert them.
it's easier for a remote app to handle it's state without routes.

the api gateway also anyway has to go through the host app's routing. So all in all, i think keeping it simple like that is going to be easier.
PS. the host app is an angularjs app.. (don't ask) but this is part of the transition out.. :)

**Comment by gioboa** [comment]
Nice, I think we can close this issue, thanks for sharing.

**Comment by gerhardcit** [comment]
@gioboa , we are revisiting this and wondering if 
```typescript
exposes: {
	'./remote-app': './src/routes/+layout.svelte',
},
```

would be advisable.
If we can handle (or ignore the remote routes on the client), can we use the remote app routing.
especiially since sveltekit v2.14.0 we can use hash routing.

so client app
https://clienthost.com/#/remote-app
renders the remote-app but want to run the sveltekit static routes in the remote
and handle all /#/remote-app/remote-routes/etc there.

however, when we exposes './remote-app': './src/routes/+layout.svelte',
the result is this.

![Image](https://github.com/user-attachments/assets/5a593d2f-19a8-4867-856f-b85d5f8158c8)

Would you have any advice or pointers to someone that solved this?

**Comment by gioboa** [comment]
So you need to handle the # routing of your remote app from the host one. Am I understanding correctly?

**Comment by gerhardcit** [comment]
First issue is that when viewing the remote app, it only shows layout.svelte content. 
One that works, I can tune the routing with hash.
I think the two is unrelated. 
1. Get routing to work first when viewing the remote app.
2. Then fine tune and start using hash routing.

somehow  using './remote-app': './src/routes/+layout.svelte', does not really use the svelte remote kit router.

**Comment by gioboa** [comment]
Can you create a basic example with a failing behaviour? At the moment I'm a bit busy but with an example I can try to investigate it when I have time

**Comment by gerhardcit** [comment]
Yes thx, I've forked the repo so you can see the effect.
https://github.com/gerhardcit/sveltekit-microfrontend-demo
